### PR TITLE
Add support for IPv6 in core and plugins

### PR DESCRIPTION
**Pull request by ledgr**
We are moving all our infrastructure to IPv6 and need this a lot.
At the moment there is only AF_INET support all over.

I have replaced everything with socket.getaddrinfo() and socket.create_connection()
This should be enough to provide IPv4 and IPv6 support, looks cleaner too.

### CODE REVIEW

**Comment by ledgr** [comment]
@gryphius

**Comment by gryphius** [comment]
thanks, much appreciated. This is indeed much cleaner. There is one syntax error in the drweb plugin which travis caught:
 `raise Exception('Could not reach drweb using network (%s, %s)' % (host, port'))`

extra `'`after port
apart from that LGTM. @neonknight , wanna have a look at it as well?

**Comment by ledgr** [comment]
I have already fixed that extra `'`. Didn't know about `python -m compileall` :)

**Comment by neonknight** [comment]
looks good at first glance (ipv4 only system). merging and testing on an ipv6 enabled box...

**Comment by neonknight** [comment]
statsd plugin was broken, fixed in 06725b0a6585756ce3d4a86e3528840f0e7faf8a

**Pull request merged**
