### PR TITLE
Py3 compatibility work

### PR DESCRIPTION
**Pull request by Caomhin**
A raft of changes to try and work on py3 compatibility. Most are relatively trivial syntax changes.

- Still runs as previously on py2
- Tests added for py3 branches

Please note: This should not be taken as production ready for py3

### CODE REVIEW

**Comment by gryphius** [comment]
just.... WOW! Thanks a LOT for this! 
I'll look over the changes next week and merge ASAP - might need a few days.

**Comment by gryphius** [comment]
the scriptfilter plugin on python2.6 complains ```SyntaxError: ("unqualified exec is not allowed in function 'exec_script' it contains a nested function with free variables",) ``` (at compile time)

I'm currently searching for a clean way to make this work on 2.6/2.7/3.x which isn't that simple actually. exec() behaves differently on py2, execfile() does not exist on py3, runpy.run_path does not exist on py2.6.

**Comment by Caomhin** [comment]
Curses, I have very limited testing options for 2.6, it's mainly throwing things at Travis and waiting for results. A version check to run the appropriate code? I've tried to minimise them as much as possible but there are a few times it's just been necessary unfortunately.

**Comment by gryphius** [comment]
yeah, I should tell travis to actually run a full compile of the source dir. atm it just runs the unit tests and scriptfilter probably doesn't have any of these either. (yet another todo). 
I tried playing around with version check, but the compiler complains as soon as it finds an "eval" call, so even if this code line would not be run in python2 the compiler doesn't like it. I'll either try to modify the plugin so it doesn't use nested functions or get rid of eval completely by using execfile in python2 and runpy.run_path on python3.

**Comment by gryphius** [comment]
I've also had to change encode/ ```decode('utf-8',errors='ignore')``` to just ```decode('utf-8','ignore')```, the ```errors``` keyword is not available in python2.6

apart from that, it's looking good now. I'll test this some more for a few days and if nothing pops up we can merge to master

**Comment by Caomhin** [comment]
Humbug! I caught that on some but not on all.

**Pull request merged**
