### PR TITLE
Python3 compatibility fixes

### PR DESCRIPTION
**Pull request by zacbri**
A few fixes for python3 incompatibilities that I ran into.
I will commit others if necessary as I come across them.

### CODE REVIEW

**Comment by zacbri** [comment]
Closing for now, this needs a bit more work...

**Comment by gryphius** [comment]
thanks for working on this! you can also just leave the PR open and prefix the title with WIP: , then we won't merge until you think it's ready

**Comment by zacbri** [comment]
ok

**Comment by zacbri** [comment]
Here are the few fixes I had to make while running my tests.

**Comment by gryphius** [comment]
thanks! We'll look into this as soon as possible. It might take a while tho, we'd like to run this on test servers for a while to make sure the addidional .encode()/decodes() don't cause any issues on python2

**Comment by neonknight** [comment]
a bunch of those changes break python 2 entirely:
- encode() -> boom! use .encode('utf-8')
- data += lump.decode('utf-8') -> boom! initialise data as b'', then wait until you received the whole line before decoding to utf-8.

**Comment by zacbri** [comment]
I've done the changes you suggested.
The unit tests ran fine so I didn't test further... sorry for the half done job.
Hope it will be OK now (I don't have a Python2 deployment to test with.

**Comment by gryphius** [comment]
> The unit tests ran fine so I didn't test further
Unfortunately this is an area where we don't have meaningful unittests yet.  I've created #133 to address this

**Comment by neonknight** [comment]
Thank you for the update, I'm currently testing this version. I'll let you know if I come across any errors.

**Comment by neonknight** [comment]
I still got a lot of errors. Encoding in python *is* a tricky thing. Please check out my workarounds in my python3 branch (so far only smtpconnector): https://github.com/neonknight/fuglu/commit/cda934452d44960623bd44765210fba8089f824f

main changes:
- introduce a try_decode method in shared.py going brute force through supported character sets
- decode incoming data in getincomingmail() to unicode with this try_decode method
- in doData() perform encode() as first task before cutting off characters

Please try if this works for you in Python 3. Also Python 2 users please try if this works for you too. In general I'm not so sure how clean my solution is, as it probably does not perform too well (in terms of CPU-cycles). An alternative suggestion (by @danBLA and @jahlives ) would be to use chardet library, which is probably not significantly better performing and adds a rather big dependency to fuglu core... any advice?

**Comment by gryphius** [comment]
I don't feel comfortable with this... en/decoding stuff without actually knowing what were'doing and hoping for the best is going to cause more troubles down the line ( broken dkim sigs, random encoding errors from broken messages, ...) . And yes, performance-wise this looks horrible. 

Given that our expertise with python3 is very limited and that these changes have a high risk of breaking python2 maybe we should take the safer approach and split them up?  I don't necessarily mean a separate branch, but maybe just the connectors, eg. have a python2 and ad python3 version of at least the smtp/esmtp connector and implement changes only there. What do you think?

**Comment by jahlives** [comment]
Another "solution" @danBLA and me see is if python3 does not convert at all and all checks are performed directly at the multi-byte string from socket. Requires changes to all checks/plugins from fuglu which work on that string.

Or fuglu works on a copy of the string which then can be converted forward/backwards/sideways ;-) without affecting any bit from original string. At the end of processing additional headers from the copy could be added to original and sent back to mta.

**Comment by gryphius** [comment]
I like the "not convert at all" approach and let plugins handle this. This would mean we define suspect.source as the raw message (bytes) and change https://github.com/gryphius/fuglu/blob/master/fuglu/src/fuglu/shared.py#L423-L431 to use message_from_bytes() in python3 which would allow plugins to perform header/content checks on the email.Message object which hopefully does the right thing (tm)

**Comment by danBLA** [comment]
Yes I think it is good to stick to the encoded string version where possible.
Regex and search can actually also be applied directly on the encoded string. In my branch (https://github.com/danBLA/fuglu/tree/python3) I have some helper functions making
sure I work with encoded or unicode strings.

**Comment by zacbri** [comment]
First of all, sorry for the poor quality of this PR.
We actually opted to run Fuglu as a Slimta policy, which makes sense for us since we use it extensively already. So we bypassed the connectors and are not running into the issues that prompted this PR anymore...

Nevertheless, I agree that carrying the encoded strings around until re-injection into the MTA is the safest solution.
We've run into a lot of problems trying to do otherwise in another project.
I'll try to have a go at it based on your suggestions, for the sake of seeing this through and not dropping the PR midway.
But if any of you beats me to it that's fine obviously :)

**Comment by jahlives** [comment]
@gryphius 
and why not convert a copy of string? That would save a lot of changes to plugins :-)
This ensures we would never send back a encoded/decoded string to mta as for example from header could come from original and not the copy that python3/fuglu mangled in any way.
If we return a mangled header (even if converted back to ascii) there is a risk of breaking stuff like dkim signatures

**Comment by neonknight** [comment]
I'm closing this PR for now as Python 3 compatibility has been implemented in #135

**Pull request closed without merging**
