### PR TITLE
Fix #56 - sqlattachment nonetype

### LINKED ISSUE #56: SQL Error NoneType attachmentrules
In postgresql (and maybe mysql) the default table scheme from http://gryphius.github.io/fuglu/plugins-index.html

`description` varchar(255) DEFAULT NULL,

If description is NULL an error is thrown.

### PR DESCRIPTION
**Pull request by wbnxvzqbrfagznggre**

### CODE REVIEW

**Comment by gryphius** [comment]
I wonder if there could be a case where we we need to read a column with a 0 (zero) value. iirc filter(None, ) would remove this as well?

**Comment by wbnxvzqbrfagznggre** [comment]
I'll provide detailed information tomorrow.

**Comment by gryphius** [comment]
```line = " ".join([value for value in row if value is not None])```
would leave zero values intact

**Comment by wbnxvzqbrfagznggre** [comment]
I come over an error when I used the attachment plugin with postgresql and leave the description empty. [ISSUE #56](https://github.com/gryphius/fuglu/issues/56)
But maybe your fix is better. I can test it on Sunday.
```
Plugin Attachment Blocker failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuglu/scansession.py", line 225, in run_plugins
    ans = plugin.examine(suspect)
  File "/usr/local/lib/python2.7/dist-packages/fuglu/plugins/attachment.py", line 442, in examine
    returnaction = self.walk(suspect)
  File "/usr/local/lib/python2.7/dist-packages/fuglu/plugins/attachment.py", line 563, in walk
    dbfile.getContent({'scope': suspect.to_domain, 'checktype': FUATT_CHECKTYPE_FN}))
  File "/usr/local/lib/python2.7/dist-packages/fuglu/extensions/sql.py", line 90, in getContent
    line = " ".join(row)
TypeError: sequence item 2: expected string or Unicode, NoneType found
```

**Comment by gryphius** [comment]
sorry, it took me a while to look at this. Currently it looks like we don't support numeric values in DBFiles anyway, so my argument about zero values doesn't really count.

**Pull request merged**
